frontend/controllers/CustomerPersonalController.php
<?php

namespace frontend\controllers;

use api\modules\v1\models\auth\User;
use api\modules\v1\models\City;
use common\helpers\CustomerHelpers;
use frontend\models\customer\CustomerBranch;
use frontend\models\customer\CustomerPersonalSearch;
use frontend\models\order\OrderPlace;
use yii\filters\AccessControl;
use yii\helpers\Url;
use yii\web\Controller;
use Yii;
use yii\web\Response;
use frontend\models\customer\CustomerPersonal;

class CustomerPersonalController extends Controller
{
    public $layout = 'customer-layout';

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actionStaff(){
        $customer_id = CustomerHelpers::getCustomerIdSite(Yii::$app->user->getId());
        if (!$customer_id) return $this->redirect(Url::to(['/customer/index']));

        if (array_key_exists('customer', Yii::$app->authManager->getRolesByUser(Yii::$app->user->getId()))){
            $model_branch = CustomerBranch::findAll([
                'customer_id' => $customer_id,
                'is_delete' => CustomerBranch::NO_DELETE
            ]);
            $model_personal = CustomerPersonal::findAll([
                'customer_id' => $customer_id,
                'is_delete' => CustomerBranch::NO_DELETE
            ]);
        }
        else {
            $model_branch = CustomerBranch::findAll([
                'customer_id' => $customer_id,
                'id' => Yii::$app->user->identity->customerPersonal->branch_id,
                'is_delete' => CustomerBranch::NO_DELETE
            ]);
            $model_personal = CustomerPersonal::findAll([
                'customer_id' => $customer_id,
                'branch_id' => Yii::$app->user->identity->customerPersonal->branch_id,
                'is_delete' => CustomerBranch::NO_DELETE
            ]);
            if (empty($model_branch)){
                Yii::$app->session->setFlash('error', 'Вы не назначены на филиал');
            }
        }
        $searchModel = new CustomerPersonalSearch([
            'customer_id' => $customer_id,
            'branch_id' => Yii::$app->request->get('branch_id') ? Yii::$app->request->get('branch_id') :
                $model_branch[0]['id']
        ]);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('staff', [
            'model_branch' => $model_branch,
            'model_personal' => $model_personal,
            'new_branch' => Yii::createObject(CustomerBranch::className()),
            'model_customer_personal' => Yii::createObject(CustomerPersonal::className()),
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * @return object|Response
     * @throws \yii\base\InvalidConfigException
     */
    public function actionAddBranch(){
        $model = new CustomerBranch();
        $customer_id = CustomerHelpers::getCustomerId(Yii::$app->user->getId());
        if ($model->load(Yii::$app->request->post())){
            $model->customer_id = $customer_id;
            $model->city_id = City::find()->one()->id;
            if ($model->save()){
                return $this->redirect(['/customer-personal/staff']);
            }
        }
        return Yii::createObject([
            'class' => 'yii\web\Response',
            'format' => Response::FORMAT_JSON,
            'data' => $model->errors,
        ]);
    }

    public function actionDeleteBranch($id){
        $model = CustomerBranch::find()->where(['id' => $id])->one();
//        $branch_id = $model->id;
        $model->is_delete = CustomerBranch::IS_DELETE;
        if ($model->save()){
//            CustomerPersonal::updateAll(['branch_id' => 0], ['branch_id' => $branch_id]);
            return $this->redirect(['/customer-personal/staff']);
        }

        return Yii::createObject([
            'class' => 'yii\web\Response',
            'format' => Response::FORMAT_JSON,
            'data' => $model->errors,
        ]);
    }

    public function actionDeletePersonal($id){
        $model = \api\modules\v1\models\customer\CustomerPersonal::find()->where(['id' => $id])->one();
        $count_no_end_order = (new \yii\db\Query())
            ->select(['ose.id'])
            ->from(['op' => 'order_place'])
            ->leftJoin(['ose' => 'order_start_end'], 'ose.order_id = op.order_id AND ose.is_finished_job = 0')
            ->where(['op.personal_id' => $model->id])
            ->count('ose.id');
        if ($count_no_end_order > 0){
            Yii::$app->session->setFlash('error', 'У данного супервайзера есть незавершенные заказы');
            return $this->redirect(['/customer-personal/staff']);
        }
        $model_user = User::findOne($model->user_id);
        $model->is_delete = CustomerPersonal::IS_DELETE;

        if ($model->save() && $model_user->setDelete()){
            return $this->redirect(['/customer-personal/staff']);
        }
        return Yii::createObject([
            'class' => 'yii\web\Response',
            'format' => Response::FORMAT_JSON,
            'data' => $model_user->errors,
        ]);
    }

    public function actionAddNewPersonal(){
        $model = new CustomerPersonal();
        if ($model->load(Yii::$app->request->post())){
            if (Yii::$app->request->post('is_edit')) {
                $model->is_edit = Yii::$app->request->post('is_edit');
                $create = $model->create(Yii::$app->request->post('is_edit'));
            }
            else {
                $create = $model->create();
            }
            if ($create != null){
                return $this->redirect(['/customer-personal/staff']);
            }
        }
        return Yii::createObject([
            'class' => 'yii\web\Response',
            'format' => Response::FORMAT_JSON,
            'data' => $model->errors,
        ]);
    }

    public function actionGetProfilePersonal(){
        if ($id = (int)Yii::$app->request->get('id')){
            $model = CustomerPersonal::findOne($id);
            $model->phone = substr($model->user->phone, 1);
            if (array_key_exists('customer', Yii::$app->authManager->getRolesByUser(Yii::$app->user->getId()))){
                $branches = CustomerBranch::findAll(['customer_id' =>
                    CustomerHelpers::getCustomerId(Yii::$app->user->getId()),
                    'is_delete' => CustomerBranch::NO_DELETE]);
            }
            else{
                $branches = CustomerBranch::findAll(['customer_id' =>
                    CustomerHelpers::getCustomerId(Yii::$app->user->getId()),
                    'id' => Yii::$app->user->identity->customerPersonal->branch_id,
                    'is_delete' => CustomerBranch::NO_DELETE]);
            }

            return $this->renderAjax('_customer-get-profile-personal', [
                'model_new_personal' => $model,
                'branches' => $branches,
                'is_edit' => true
            ]);
        }
        return false;
    }
}

frontend/views/customer-personal/_customer-get-profile-personal.php
<?php


?>
<script>
    $.magnificPopup.open({
        items: {
            src: '#change-staff-popup'
        },
        type: 'inline'
    });
    $('.close-popup').click(function(e) {
        e.preventDefault();
        $.magnificPopup.close();
    });
</script>
<div id="change-staff-popup" class="zoom-anim-dialog popup add-staff-popup">
    <h2>Изменить данные сотрудника</h2>
    <?= $this->render('@frontend/widgets/views/_new-personal_form', [
        'model_new_personal' => $model_new_personal,
        'branches' => $branches,
        'is_edit' => $is_edit
    ]) ?>
</div>

frontend/views/customer-personal/staff.php
<?php

use frontend\models\customer\CustomerPersonal;
use frontend\widgets\NewPersonalEditWidget;
use frontend\widgets\NewPersonalWidget;
use yii\grid\GridView;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\widgets\Pjax;

$this->title = 'Персонал';
?>

<section class="staff">
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="staff_branches">
                    <p>Филиалы</p>
                    <ul class="staff_branches-list">
                        <?php foreach ($model_branch as $item):?>
                            <?php if (Yii::$app->request->get('branch_id')):?>
                                <li class="<?= Yii::$app->request->get('branch_id') == $item->id ? 'active' : '' ?>">
                            <?php else:?>
                                <li class="<?= $model_branch[0]['id'] == $item->id ? 'active' : '' ?>">
                            <?php endif;?>
                                <a href="<?= Url::to(['/customer-personal/staff', 'branch_id' => $item->id]) ?>"><?= $item->branch ?></a>
                                <div class="staff_table-more-btn">
                                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><circle cx="256" cy="256" r="64"/><circle cx="256" cy="448" r="64"/><circle cx="256" cy="64" r="64"/></svg>
                                    <ul>
<!--                                        <li><a href="#">Редактировать</a></li>-->
                                        <li>
                                            <?=
//                                            Html::a('Удалить', ['delete-branch', 'id' => $item->id], [
//                                                'data' => [
//                                                    'confirm' => 'Действительно хотите удалить?',
//                                                    'method' => 'post',
//                                                ],
//                                            ])
                                            $dataProvider->totalCount == 0 ? Html::a('Удалить', ['delete-branch', 'id' => $item->id], [
                                                'data' => [
                                                    'confirm' => 'Действительно хотите удалить?',
                                                    'method' => 'post',
                                                ],
                                            ]) : Html::a('Удалить', '#', [
                                                'onclick' => 'alert("Вы не можете удалить филиал с сотрудниками. Переместите либо удалите сотрудников")'])

                                            ?>
                                        </li>
                                    </ul>
                                </div>
                            </li>
                        <?php endforeach;?>
                    </ul>
                    <?php if (array_key_exists('customer',
                        Yii::$app->authManager->getRolesByUser(Yii::$app->user->getId()))):?>
                        <a href="#add-brahch-popup"  class="open-popup staff_branches-add">+ Добавить филиал</a>
                    <?php endif;?>
                </div>
            </div>
            <div class="col-lg-9">
                <div class="overflow-table">
                    <?= GridView::widget([
                        'dataProvider' => $dataProvider,
                        'showHeader'=> false,
                        'id' => false,
                        'tableOptions' => [
                            'class' => 'staff_table'
                        ],
                        'layout' => '{items}<br>{pager}',
                        'pager' => [
                            'options' => ['class' => 'pagination__list'],
                            'nextPageCssClass' => 'pagination__next',
                            'prevPageCssClass' => 'pagination__prev',
                            'activePageCssClass' => 'active',
                            'maxButtonCount' => 3,
                            'prevPageLabel' => '',
                            'nextPageLabel' => '',
                        ],
                        'columns' => [
                            'id',
                            [
                                'format' => 'raw',
                                'value' => function ($model) {
                                    return $model->role == 'supervisor' ? 'Супервайзер' : 'Администратор';
                                },
                            ],
                            [
                                'format' => 'raw',
                                'value' => function ($model) {
                                    return $model->user->phone;
                                },
                            ],
                            [
                                'format' => 'raw',
                                'value' => function ($model) {
                                    return $model->last_name . ' ' . $model->name . ' ' . $model->middle_name;
                                },
                            ],
                            [
                                'format' => 'raw',
                                'value' => function ($model) {
                                    return '<div class="staff_table-more-btn">
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><circle cx="256" cy="256" r="64"/><circle cx="256" cy="448" r="64"/><circle cx="256" cy="64" r="64"/></svg>
                            <ul>
                              <li><a href="#change-staff-popup" class="open-popup open-popup_change_form" data-id="' . $model->id . '">Редактировать</a></li>
                              <li>
                                    ' . Html::a('Удалить', ['delete-personal', 'id' => $model->id], [
                                            'data' => [
                                                'confirm' => 'Действительно хотите удалить?',
                                                'method' => 'post',
                                            ],
                                        ]) .' </li>
                            </ul>
                          </div>';
                                }
                            ],
                        ],
                    ]); ?>
                </div>
                <div class="staff_button">
                    <?php if (!empty($model_branch)): ?>
                        <a href="#add-staff-popup" class="orange-btn open-popup"><span>+</span>Добавить персонал</a>
                    <?php else: ?>
                        <a href="#" onclick="alert('Добавьте филиал');" class="orange-btn"><span>+</span>Добавить персонал</a>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
</section>
<div id="add-brahch-popup" class="zoom-anim-dialog mfp-hide popup add-brahch-popup">
    <h2>Создать новый филиал</h2>
        <?php $form = ActiveForm::begin([
            'action' => Url::to('/customer-personal/add-branch'),
            'validateOnBlur' => false,
        ]); ?>
            <div class="form-group">
                <label for="ab1">Филиал</label>
                <?= $form->field($new_branch, 'branch')
                    ->textInput(['placeholder' => 'Название филиала',
                        'onkeydown' => "return event.key != 'Enter';"])
                    ->label(false) ?>
            </div>
            <div class="add-brahch-popup-buttons">
                <button class="grey-btn close-popup">Отмена</button>
                <button type="submit" class="orange-btn">Создать</button>
            </div>
        <?php ActiveForm::end(); ?>
</div>

<?= NewPersonalWidget::widget() ?>
<?//= NewPersonalEditWidget::widget() ?>
<div class="open_change_personal"></div>
<?php
$script_open_popup = <<<JS
$('.open-popup_change_form').click(function() {
    var id = $(this).attr('data-id'); 
    $.get('/customer-personal/get-profile-personal', {"id":id}, function(response) {
        if (response != false) {
            $('.open_change_personal').empty();
            $('.open_change_personal').append(response);
        }
        else alert('Неверный запрос');
    });
});

JS;
$this->registerJs($script_open_popup);
?>